apiVersion: v1
kind: Service
metadata:
  name: ln1
  namespace: teol
  labels:
    app: gateway
spec:
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
  selector:
    app: ln1
---
apiVersion: v1
kind: Service
metadata:
  name: ln1-production
  namespace: teol
  labels:
    app: gateway
spec:
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
  selector:
    app: ln1-production
