apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CURRENT_SERVICE}
  namespace: ${NAMESPACE}
  labels:
    app: ${CURRENT_SERVICE}
spec:
  selector:
    matchLabels:
      app: ${CURRENT_SERVICE}
      tier: ${SERVICE_TYPE}
  template:
    metadata:
      labels:
        app: ${CURRENT_SERVICE}
        tier: ${SERVICE_TYPE}
    spec:
      containers:
        - name: ${CURRENT_SERVICE}
          image: ghcr.io/${CODENAME}/${NAMESPACE}/${CURRENT_SERVICE}:${TAG}
          envFrom:
            - secretRef:
                name: ln1-production
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
            limits:
              memory: 10240Mi
              cpu: 5000m
