name: DataHive LN1 Production View

on:
  push:
    branches: [releases/**]
    paths:
      - "view/**"
      - ".github/workflows/view.yml"
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-production.datahive.p10node.com-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-production.datahive.p10node.com-

      - name: Install dependencies
        shell: bash
        working-directory: ./view
        run: |
          pnpm --ignore-workspace install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build Website
        working-directory: ./view
        run: pnpm build
        env:
          VITE_STAGE: production
          VITE_WC_PROJECT_ID: 785959e994f4aa0df486cb6affa2cb67
          VITE_API_URL: https://api.datahive.p10node.com
          VITE_GOOGLE_GA: G-PED69QCEDZ
          VITE_GOOGLE_RECAPTCHA: 6LcJxVkqAAAAAG5DDvY843EJHZXY95kuiSMWzDDo

      - name: Push data to S3
        working-directory: ./view
        run: aws s3 sync dist/ s3://ln1.datahive.p10node.com/ --acl public-read

      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:

            Commit message: ${{ github.event.commits[0].message }}

            Repository: https://github.com/${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

            Latest production updated: https://ln1.datahive.p10node.com
